### ISSUE TITLE
expired certificate on tg.dev

### ISSUE THREAD

**Issue by ffrappo** [sveggiani/react-telegram-comments#1]
### Hello, writing to inform you that the certificate has expired

btw i'm using your package in https://www.foolstools.net and it's truly good :)

![image](https://user-images.githubusercontent.com/1463322/121020406-a319bd80-c7a0-11eb-9830-a2f2469fcfa0.png)

**Comment by ffrappo** [comment]
Resolved :)

**Comment by sveggiani** [comment]
@ffrappo this is not related to this library but an issue with Telegram servers.
