### ISSUE TITLE
Can I use already existing chat?

### ISSUE THREAD

**Issue by SaqoTadevosyan** [sveggiani/react-telegram-comments#2]
Like I have telegram channel , in my tg channel I share post , the same post I have in my website.
I want to add comment from widget inside comments block to my post in telegram channel

**Comment by sveggiani** [comment]
I'm sorry @SaqoTadevosyan , I couldn't understand your requirement. Could you please re-elaborate?

**Comment by SaqoTadevosyan** [comment]
I had post in my telegram channel and I want show on my web site comments from that post

**Comment by sveggiani** [comment]
I think you can do that with https://core.telegram.org/widgets/discussion, but that's something not supported by this library.
